# Generated by Django 3.2.9 on 2022-01-11 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
