# Generated by Django 3.2.9 on 2022-01-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend_api', '0003_delete_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='puzzles',
            field=models.IntegerField(default=0),
        ),
    ]
